export const ERROR_CODES = {
  INVALID_PHONE_FORMAT: 'INVALID_PHONE_FORMAT',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  INVALID_OTP: 'INVALID_OTP',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_ALREADY_USED: 'OTP_ALREADY_USED',
  TOO_MANY_OTP_ATTEMPTS: 'TOO_MANY_OTP_ATTEMPTS',
  OTP_REQUEST_RATE_LIMIT: 'OTP_REQUEST_RATE_LIMIT',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  USER_SUSPENDED: 'USER_SUSPENDED',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  VENDOR_NOT_FOUND: 'VENDOR_NOT_FOUND',
  VENDOR_PENDING_APPROVAL: 'VENDOR_PENDING_APPROVAL',
  VENDOR_SUSPENDED: 'VENDOR_SUSPENDED',
  EMAIL_ALREADY_IN_USE: 'EMAIL_ALREADY_IN_USE',
  STORE_NAME_TAKEN: 'STORE_NAME_TAKEN',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
